pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["absences.html","Absences","Navigation: Dialogs Add/Edit Profile Absences Absences Tab If you have appropriate rights the user profile dialog also shows the current absence c...",""],
["absences_2.html","Avatar","Navigation: Dialogs Add/Edit Profile Avatar Avatar Tab Users can be assigned an avatar, a thumbnail like image. This avatar will show when moving ...",""],
["absence_assigment.html","Absence to Group Assignment","Navigation: Administration Absence to Group Assignment Absence Assignment In this dialog you can assign the absence type to certain groups only. B...",""],
["absence_icons.html","Absence Icon","Navigation: Administration Absence Icon Absence Icon TeamCal Pro also supports absence icons. These icons will be displayed in the calendar instea...",""],
["administration.html","Administration","Navigation: No topics above this level Administration If your account holds administrator rights the Tools Menu contains the Administration menu. ...",""],
["announcement_display.html","Announcement Page","Navigation: Main Interface Announcement Page Announcement Page When a user is logged in he can display his announcement page. He can either do tha...",""],
["calendar_display.html","Calendar Display","Navigation: Main Interface Calendar Display Calendar Calendar Display The calendar display uses the same format for each month. You see the month ...",""],
["configuration.html","Configuration","Navigation: Administration Configuration TeamCal Pro Configuration Administrators have access to the TeamCal Pro Configuration via the Administrat...",""],
["daynote_dialog.html","Daynote","Navigation: Dialogs Daynote Daynote Dialog You can store a note of 80 characters for each day. A day holding a day note will be displayed with a s...",""],
["dialogs.html","Dialogs","Navigation: No topics above this level Dialogs Most of the settings and options in TeamCal Pro are displayed and changed in dialog windows, which ...",""],
["edit_profile.html","Add/Edit Profile","Navigation: Dialogs Add/Edit Profile The user profile dialog uses tabs to display user specific information for viewing or editing. Edit Profile T...",""],
["group_assignment.html","Group Assignment","Navigation: Administration Group Assignment Group Assignment The Group Assignment page offers a different, though more convenient way to change us...",""],
["homepage.html","Homepage","Navigation: Main Interface Homepage The Homepage can be used to display a global message to the TeamCal Pro users. It will always be available, al...",""],
["installation.html","Installation","Navigation: No topics above this level Installation Installing TeamCal Pro has been made much easier with version 3.0. An installation script take...",""],
["introduction.html","Introduction","Navigation: No topics above this level Introduction TeamCal Pro is a web-based application utilizing PHP and a MySQL database. It&#39;s generic purpos...",""],
["legend_dialog.html","Legend","Navigation: Dialogs Legend Legend Dialog The Legend dialog explains terms, symbols and colors that are used in the calendar display. The terms for...",""],
["login.html","Login","Navigation: Dialogs Login Login Dialog Use the login dialog to login to TeamCal Pro. A username and a password must be supplied. Buttons [Login] w...",""],
["main_interface.html","Main Interface","Navigation: No topics above this level Main Interface TeamCal Pro Main Interface TeamCal&#39;s Main Screen shows an application header, a menu bar , a...",""],
["manage_absence_types.html","Absence Types","Navigation: Administration Absence Types Manage Absences The Manage Absence Types page can be used to configure each absence type to your requirem...",""],
["manage_database.html","Database Maintenance","Navigation: Administration Database Maintenance Manage Database The Database Management is new in Version 2.2. It offers a clean-up feature for ol...",""],
["manage_declination.html","Declination","Navigation: Administration Declination Declination Management The declination management basically offers a check how many colleagues are already ...",""],
["manage_groups.html","Groups","Navigation: Administration Groups Manage Groups The Manage Groups page will list all currently configured groups in TeamCal Pro. The box is offeri...",""],
["manage_holiday_types.html","Holiday Types","Navigation: Administration Holiday Types Manage Holiday Types The Manage Holiday Types box will list all currently configured holiday types in Tea...",""],
["manage_regions.html","Regions","Navigation: Administration Regions Manage Regions Dialog Regions in TeamCal Pro are used to provide different base calendars. You can set up diffe...",""],
["manage_users.html","Users","Navigation: Administration Users Userlist Search You can search for user first names and last names. Type in your search string in the search box ...",""],
["membership.html","Membership","Navigation: Dialogs Add/Edit Profile Membership Membership Tab Users can be member of multiple groups. In this section you can check the groups th...",""],
["menu.html","Menu Bar","Navigation: Main Interface Menu Bar Menu TeamCal Pro Menu TeamCal Pro Admin Menu The following menus will be shown in the menu bar based on your p...",""],
["message_center.html","Message Center","Navigation: Dialogs Message Center Message Center Use the message center to send an e-Mail or an Announcement to a single user, a group or to all ...",""],
["month_template.html","Month Template","Navigation: Dialogs Month Template The month template dialog displays a specific month of a specific region providing the option to store day note...",""],
["options.html","Options","Navigation: Dialogs Add/Edit Profile Options Options Tab In the upper portion of this tab you can set: Show own groups only With this switch on, t...",""],
["other.html","Other","Navigation: Dialogs Add/Edit Profile Other Other Tab Additional information for a user can be entered in the Other tab. Custom 1 - 5 Five custom f...",""],
["permissions.html","Permissions","Navigation: Administration Permissions TeamCal Pro Permissions Page With the introduction of release 3.5.000 the permission management has complet...",""],
["personal_data.html","Personal Data","Navigation: Dialogs Add/Edit Profile Personal Data Personal Data Tab Fill in the user information here. Username: You cannot change your username....",""],
["privileges.html","Account","Navigation: Dialogs Add/Edit Profile Account Account Tab This dialog tab is only available if you hold administrator rights. TeamCal Pro supports ...",""],
["register.html","User Registration","Navigation: Dialogs User Registration User Registration TeamCal Pro supports user self registration. A user can submit his basic personal data so ...",""],
["statistics_display.html","Global Statistics Display","Navigation: Main Interface Global Statistics Display The statistics page offers statistical information of the current database based on a specifi...",""],
["statistics_display_2.html","Statistics Display_2","Navigation: Main Interface Remainder Current Year This statistics page offers a visual representation of the remainders of each absence type for e...",""],
["system_log_page.html","System Log Page","Navigation: Administration System Log Page The System Log page has changed as of release 3.5.000. It now combines, the System Log itself and the L...",""],
["teamcal_pro_license.html","TeamCal Pro License","Navigation: Introduction TeamCal Pro License TeamCal Pro was developed by George Lewe ( http://www.lewe.com ). TeamCal Pro is free software; it ma...",""],
["template_user.html","Template User","Navigation: Administration Template User Overview Template users offer a way to set absences for a whole group in one shot. All absences set for a...",""],
["theme_support.html","Theme Support","Navigation: Administration Theme Support Theme selection on the Configuration page TeamCal Pro supports themes. A theme is a collection of styles ...",""],
["upload_dialog.html","Icon Upload Dialog","Navigation: Administration Icon Upload Dialog Upload Dialog The upload dialog provides an interface to upload image files to the TeamCal Pro web s...",""],
["user_calendar.html","User Calendar","Navigation: Dialogs User Calendar User Calendar Dialog The user calendar dialog displays a specific month and shows a row with radio boxes for eac...",""],
["user_import.html","User Import","Navigation: Administration User Import User Import Administrators may import user accounts via a CSV file. This shall speed up the process of user...",""],
["view_profile.html","View Profile","Navigation: Dialogs View Profile View Profile Dialog The view user profile dialog shows all relevant user information and offers the option to sen...",""],
["year_calendar_display.html","Year Calendar Display","Navigation: Main Interface Year Calendar Display New in version 3.0 is the year calendar display. It shows the absences of one user for a full cal...",""]];
